return {
  ensure_installed = {
    -- Formatters & Linters
    "ktlint",
    "rustfmt",
    "gofumpt",
    "golangci-lint",
    "gdtoolkit",
    "gitleaks",
    "gitlint",
    "markdownlint",
    "markuplint",
    "nginx-config-formatter",
    "sql-formatter",
    "stylua",
    "yamllint",

    -- Debuggers
    "kotlin-debug-adapter",
    "bash-debug-adapter",
    "dart-debug-adapter",
    "chrome-debug-adapter",
    "go-debug-adapter",
    "local-lua-debugger-vscode",

    -- Language Servers
    "powershell-editor-services",
    "gradle-language-server",
    "golangci-lint-langserver",
    "azure-pipelines-language-server",
    "bash-language-server",
    "csharp-language-server",
    "css-lsp",
    "cypher-language-server",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "graphql-language-service-cli",
    "html-lsp",
    "json-lsp",
    "jsonld-lsp",
    "kotlin-language-server",
    "lua-language-server",
    "nginx-language-server",
    "omnisharp",
    "omnisharp-mono",
    "postgrestools",
    "pyment",
    "rust-analyzer",
    "rust_hdl",
    "rustywind",
    "sqlls",
    "sqls",
    "terraform",
    "terraform-ls",
    "wasm-language-tools",
    "yaml-language-server",
  },

  auto_update = false,
  run_on_start = true,
}

